SELECT E.ID,
    CASE
        WHEN E.PR <= 0.25 THEN 'CRITICAL'
        WHEN E.PR <= 0.5 THEN 'HIGH'
        WHEN E.PR <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID,
        PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PR
    FROM ECOLI_DATA
) AS E
ORDER BY E.ID ASC;