# 최초의 대장균 개체의 PARENT_ID 는 NULL 값
# 각 분기(QUARTER)별 분화된 대장균의 개체의 총 수(ECOLI_COUNT)를 출력
# 각 분기에는 'Q' 를 붙이고 분기에 대해 오름차순으로 정렬
# 대장균 개체가 분화되지 않은 분기는 없다.
SELECT 
    CASE
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN "1Q"
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN "2Q"
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN "3Q"
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12 THEN "4Q"
    END AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY 
    CASE
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN "1Q"
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN "2Q"
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN "3Q"
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12 THEN "4Q"
    END
ORDER BY 1 ASC;