# SELECT HISTORY_ID,
# ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1)
#       * ((100 - DISCOUNT_RATE) / 100), 0) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR AS a 
#       JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON a.CAR_ID = b.CAR_ID 
#       LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c ON a.CAR_TYPE = c.CAR_TYPE
# AND c.DURATION_TYPE = (
#     CASE
#         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
#         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
#         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
#     END
# )
# WHERE a.CAR_TYPE = '트럭'
# ORDER BY FEE DESC, b.HISTORY_ID DESC;




SELECT HISTORY.HISTORY_ID, ROUND((DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1) 
                                 * CAR.DAILY_FEE 
                                 * (100 - COALESCE(PLAN.DISCOUNT_RATE, 0)) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
JOIN CAR_RENTAL_COMPANY_CAR AS CAR
ON HISTORY.CAR_ID = CAR.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON CAR.CAR_TYPE = PLAN.CAR_TYPE 
AND PLAN.DURATION_TYPE = (CASE WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 90 THEN '90일 이상'
                          WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 30 THEN '30일 이상'
                          WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 7 THEN '7일 이상'
                          END
                         )
WHERE CAR.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;