SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
# FROM DEVELOPERS D CROSS JOIN SKILLCODES S => Cartesian product
# b'010100000010000'
WHERE SKILL_CODE & (
    SELECT SUM(CODE)
    FROM SKILLCODES 
    WHERE CATEGORY = 'Front End'
) > 0
ORDER BY ID ASC;
