SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (
    SELECT D.ID
    FROM SKILLCODES S
    WHERE (S.CODE & D.SKILL_CODE) > 0 AND S.NAME IN ('Python', 'C#')
)
ORDER BY D.ID ASC;