SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
    ABS(E.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV,
    ED.ID
FROM ECOLI_DATA ED
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) E ON YEAR(ED.DIFFERENTIATION_DATE) = E.YEAR
ORDER BY 1 ASC, 2 ASC