SELECT HISTORY_ID, CAR_ID, 
DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE,
DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
IF(DATEDIFF(END_DATE, START_DATE) >= 29, '장기 대여', '단기 대여') AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) = '09'
ORDER BY HISTORY_ID DESC;

# DATEDIFF(2022-09-30, 2022-09-01) -> 30일 대여
# DATE_FORMAT 안쓰고 그냥 START_DATE, END_DATE하면 날짜뿐만 아니라 뒤에 시간도 같이 출력됨.
# MONTH() 사용 시 = 뒤에 '09', 09, 9 전부 가능